### ISSUE TITLE
Does not seem to be working for 4.19 or 20

### ISSUE THREAD

**Issue by Adibhatt95** [pushmatrix/marionettevr#1]
Hello I tried opening the project for ue 4.19 version it doesn't work for this at all, is there any way to make it work?

**Comment by Adibhatt95** [comment]
in fact the VDTension rope isn't a thing in the later versions of the VD plugin, did you write that on your own?

**Comment by pushmatrix** [comment]
Hmmm most likely not. This wasn't designed for later engine versions.

I didn't write the VDTension thing either :(
